services:
  fetchtify:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres

  postgres:
    image: postgres:16
    container_name: fetchtify-postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h 127.0.0.1" ]
      interval: 5s
      timeout: 10s
      retries: 5
    environment:
      POSTGRES_DB: artists_storage
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secretpassword